# Introduction to Pytorch: Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

In [1]:
import torch
import numpy as np

## Initializing the tensors

1. Directly from Data

In [2]:
data = [[1, 2], [3, 4],[5, 6]]
x_data = torch.tensor(data)
x_data, x_data.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

2. From a numpy array

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np, x_np.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

3. From another tensor: The created tensor retains the properties (shape, datatype) of argument tensor

In [4]:
ones = torch.ones_like(x_data)
print(f'Ones tensor :\n{ones}\n')

rand_values = torch.rand_like(x_data, dtype = torch.float)
print(f'\nRandom tensor : \n{rand_values, rand_values.dtype}')

Ones tensor :
tensor([[1, 1],
        [1, 1],
        [1, 1]])


Random tensor : 
(tensor([[0.2427, 0.8274],
        [0.5268, 0.0331],
        [0.1863, 0.9912]]), torch.float32)


4. With random and constant values

In [5]:
shape = (2, 3, 5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.5341, 0.5987, 0.0666, 0.7801, 0.2769],
         [0.8917, 0.6204, 0.8767, 0.5018, 0.2394],
         [0.0055, 0.7208, 0.7401, 0.2762, 0.5986]],

        [[0.3267, 0.4563, 0.2142, 0.9129, 0.4903],
         [0.6527, 0.5377, 0.1881, 0.8924, 0.9190],
         [0.2560, 0.4477, 0.9611, 0.9719, 0.4559]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


## Attributes of a Tensor

Tensor attributes describe shape, datatype, and device

In [6]:
tensor = torch.rand(3, 4)

print(f'Shape of the tensor is {tensor.shape}\n')
print(f'Datatype of the tensor is {tensor.dtype}\n')
print(f'Device of the tensor is  stored in {tensor.device}\n')


Shape of the tensor is torch.Size([3, 4])

Datatype of the tensor is torch.float32

Device of the tensor is  stored in cpu



## Operations on Tensor

https://pytorch.org/docs/stable/torch.html

cpu to gpu

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
tensor

tensor([[0.5750, 0.6217, 0.7791, 0.4904],
        [0.9978, 0.1180, 0.2091, 0.0632],
        [0.9437, 0.9374, 0.3806, 0.3625]])

Standard numpy-like indexing and slicing:

In [9]:
tensor = torch.ones(4, 5)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,2] = 0 # 2nd index = 0
print(tensor)

First row: tensor([1., 1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


Joining tensors

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]])


Arithmetic Operations

In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
print(f'Y1 = {y1}\n')
y2 = tensor.matmul(tensor.T)
print(y1==y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f'Y3 = {y3}\n')

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
print(f'z1 = {z1}\n')
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

Y1 = tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
Y3 = tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

z1 = tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])



tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

Single element tensors

In [12]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(16.)
16.0 <class 'float'>


In-place operations

In [13]:
print(f"{tensor} \n")
tensor.add_(10)
print(tensor)

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]]) 

tensor([[11., 11., 10., 11., 11.],
        [11., 11., 10., 11., 11.],
        [11., 11., 10., 11., 11.],
        [11., 11., 10., 11., 11.]])


## Bridge with NumPy

Tensor to NumPy Array

In [14]:
t = torch.ones(2,3)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([[1., 1., 1.],
        [1., 1., 1.]])
n: [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([[2., 2., 2.],
        [2., 2., 2.]])
n: [[2. 2. 2.]
 [2. 2. 2.]]


NumPy Array to Tensor

In [16]:
n = np.ones([2, 3])
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [[1. 1. 1.]
 [1. 1. 1.]]
t: tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
n: [[2. 2. 2.]
 [2. 2. 2.]]


Changes in the NumPy array reflects in the tensor and vice versa.